version: "3.5"

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: apicurio-registry
      POSTGRES_PASSWORD: password
      PG_DATA: postgres
    volumes:
      - postgres:/data/postgres
  app:
    image: apicurio/apicurio-registry-sql:latest-snapshot
    ports:
      - 8080:8080
    environment:
      APICURIO_STORAGE_KIND: "sql"
      APICURIO_STORAGE_DB_KIND: "postgresql"
      REGISTRY_DATASOURCE_URL: "jdbc:postgresql://postgres/apicurio-registry"
      REGISTRY_DATASOURCE_USERNAME: apicurio-registry
      REGISTRY_DATASOURCE_PASSWORD: password
    depends_on:
      - postgres

volumes:
  postgres:
