apiVersion: apps/v1
kind: Deployment
metadata:
  name: apicurio
  namespace: apicurio
  labels:
    app: apicurio
spec:
  replicas: 3
  selector:
    matchLabels:
      app: apicurio
  template:
    metadata:
      labels:
        app: apicurio
    spec:
      containers:
      - name: apicurio
        image: "apicurio/apicurio-registry:latest-snapshot"
        ports:
        - name: schema-registry
          containerPort: 8080
          protocol: TCP
        # resources:
        #   requests:
        #     memory: "64Mi"
        #     cpu: "250m"
        #   limits:
        #     memory: "1Gi"
        #     cpu: "2Gi"
# https://github.com/Apicurio/apicurio-registry/blob/main/examples/openshift-template/apicurio-registry-template-mem.yml