# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: apicurio-ingress
#   namespace: apicurio
#   annotations:
#     nginx.ingress.kubernetes.io/rewrite-target: /$1
# spec:
#   rules:
#     - host: apicurio-registry-example.example
#       http:
#         paths:
#           - path: /
#             pathType: Prefix
#             backend:
#               service:
#                 name: apicurio
#                 port:
#                   number: 8080