apiVersion: v1
kind: Service
metadata:
  labels:
    app: apicurio
  name: apicurio
  namespace: apicurio
spec:
  ports:
  - nodePort: 31906
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: apicurio
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}