name: test-merge-pr
on: 
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: write
  pull-requests: write

jobs:
  first-job:
    if: ${{ ! startsWith( github.head_ref, 'release-please*') }}
    runs-on: ubuntu-latest
    steps:
      - name: first-step
        run: echo "Hello World!"
      - name: second-step
        run: echo "second step"
  second-jobs:
    if: ${{ ! startsWith( github.head_ref, 'release-please*') }}
    runs-on: ubuntu-latest
    environment: dev
    needs: [first-job]
    steps:
      - name: second-job-first-step
        run: echo "inside of second jobs"