name: test-merge-pr
on: 
  push:
    branches:
      - main
      - '!release-please*'
  pull_request:


permissions:
  contents: write
  pull-requests: write

jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: first-step
        run: echo "Hello World!"
      - name: second-step
        run: echo "second step"
  second-jobs:
    runs-on: ubuntu-latest
    environment: dev
    needs: [first-job]
    steps:
      - name: second-job-first-step
        run: echo "inside of second jobs"