on:
  push:
    branches:
      - main
name: on-merge

jobs:
  on-merge-first-job:
    runs-on: ubuntu-latest
    steps:
      - name: on-merge-first
        run: echo "first step Hello World!"
      - name: on-merge-second-step
        run: echo "on merge second step"
  on-merge-second-jobs:
    runs-on: ubuntu-latest
    environment: dev
    needs: [first-job]
    steps:
      - name: second-job-first-step
        run: echo "inside of second jobs"